# Generated by Django 4.0.5 on 2022-06-26 19:17

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kate', '0003_alter_profile_resume'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('about_pic', cloudinary.models.CloudinaryField(max_length=255, verbose_name='about')),
                ('about', models.TextField()),
                ('contact', models.EmailField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='resume',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='resume'),
        ),
    ]
