# Generated by Django 4.0.5 on 2022-06-30 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kate', '0007_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='contact_img',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='url',
        ),
    ]
