# Generated by Django 4.0.5 on 2022-07-02 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kate', '0008_remove_contact_contact_img_remove_contact_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='resume',
            field=models.URLField(blank=True, null=True),
        ),
    ]
